// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124084055_CoffeeClasses")]
    partial class CoffeeClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("API.Entities.Coffee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaffeineLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoffeeDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoffeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoastLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coffees");
                });

            modelBuilder.Entity("API.Entities.CoffeeFlavorProfile", b =>
                {
                    b.Property<string>("CoffeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CoffeeId", "FlavorProfileId");

                    b.HasIndex("FlavorProfileId");

                    b.ToTable("CoffeeFlavorProfiles");
                });

            modelBuilder.Entity("API.Entities.CoffeePreference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoffeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeId");

                    b.HasIndex("UserId");

                    b.ToTable("CoffeePreferences");
                });

            modelBuilder.Entity("API.Entities.CoffeeRecommendation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoffeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Score")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ViewAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasAccepted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeId");

                    b.HasIndex("UserId");

                    b.ToTable("CoffeeRecommendations");
                });

            modelBuilder.Entity("API.Entities.CoffeeUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CoffeeUsers");
                });

            modelBuilder.Entity("API.Entities.FlavorProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FlavorProfiles");
                });

            modelBuilder.Entity("API.Entities.CoffeeFlavorProfile", b =>
                {
                    b.HasOne("API.Entities.Coffee", "Coffee")
                        .WithMany("CoffeeFlavorProfiles")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.FlavorProfile", "FlavorProfile")
                        .WithMany("CoffeeFlavorProfiles")
                        .HasForeignKey("FlavorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coffee");

                    b.Navigation("FlavorProfile");
                });

            modelBuilder.Entity("API.Entities.CoffeePreference", b =>
                {
                    b.HasOne("API.Entities.Coffee", "Coffee")
                        .WithMany("CoffeePreferences")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.CoffeeUser", "User")
                        .WithMany("CoffeePreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coffee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entities.CoffeeRecommendation", b =>
                {
                    b.HasOne("API.Entities.Coffee", "Coffee")
                        .WithMany("CoffeeRecommendations")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.CoffeeUser", "User")
                        .WithMany("CoffeeRecommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coffee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entities.CoffeeUser", b =>
                {
                    b.HasOne("API.Entities.AppUser", "AppUser")
                        .WithOne("CoffeeUser")
                        .HasForeignKey("API.Entities.CoffeeUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Navigation("CoffeeUser")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Entities.Coffee", b =>
                {
                    b.Navigation("CoffeeFlavorProfiles");

                    b.Navigation("CoffeePreferences");

                    b.Navigation("CoffeeRecommendations");
                });

            modelBuilder.Entity("API.Entities.CoffeeUser", b =>
                {
                    b.Navigation("CoffeePreferences");

                    b.Navigation("CoffeeRecommendations");
                });

            modelBuilder.Entity("API.Entities.FlavorProfile", b =>
                {
                    b.Navigation("CoffeeFlavorProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
